<?php
/**
* @file
* A description of what your module does.
*/


/**
 * Implements hook_permission().
 */
function weather_permission() {
    return array(
        'administer weather' => array(
            'title' => t('Administer Weather app.'),
            'description' => t('Perform administration tasks for Weather app.'),
        ),
        'access weather list' => array(
            'title' => t('Administer Weather app.'),
            'description' => t('Perform administration tasks for Weather app.'),
        ),
    );
}

/**
 * Implements hook_menu().
 */
function weather_menu(){
    $items['admin/config/weather'] = array(
        'title' => 'Weather App Settings',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'weather_admin_list',
        'access arguments' => array('access weather list'),
    );
    $items['admin/config/weather/list'] = array(
        'title' => 'Weather App List',
        'type' => MENU_DEFAULT_LOCAL_TASK
    );
    $items['admin/config/weather/form'] = array(
      'title' => 'Weather App Form',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('weather_admin_form'),
      'access arguments' => array('administer weather'),
    );
    return $items;
}

function weather_admin_list(){
    $results = db_query("SELECT * FROM {weather}");

    $header = array(t('Name'), t('Longitude'), t('Latitude'));
    $rows = array();

    foreach($results as $result){
        $rows[] = array(
            $result->name,
            $result->longitude,
            $result->latitude,
        );
    }
    return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Administration form for Weather app.
 */
function weather_admin_form($form, &$form_state){

    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'Name',
        '#size' => 20,
        '#maxlength' => 20,
        '#required' => TRUE,
        '#description' => t('Name of the location.')
    );

    $form['longitude'] = array(
        '#type' => 'textfield',
        '#title' => 'Longitude',
        '#size' => 20,
        '#maxlength' => 20,
        '#required' => TRUE,
        '#default_value' => '0.00000',
        '#description' => t('Longitudinal coordinates.')
    );

    $form['latitude'] = array(
        '#type' => 'textfield',
        '#title' => 'Latitude',
        '#size' => 20,
        '#maxlength' => 20,
        '#required' => TRUE,
        '#default_value' => '0.00000',
        '#description' => t('Latitudinal coordinates.')
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Submit')
    );

    return $form;
}

function weather_admin_form_submit($form, &$form_state){
    $w_id = db_insert('weather')
        ->fields(array(
            'name' => $form_state['values']['name'],
            'latitude' => $form_state['values']['latitude'],
            'longitude' => $form_state['values']['longitude'],
        ))
        ->execute();
    drupal_set_message(t('Your form has been submitted!'));
}

function weather_block_info() {

    $blocks['weather_block'] = array(
        'info' => t('Weather Info'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function weather_block_view($delta = '') {
    $city = new City;
    $block = array();
    switch ($delta) {
        case 'weather_block':
            $block['subject'] = t('Weather Infos');

            $results = db_query("SELECT * FROM {weather}");

            $header = array(t('Location'), t('Temperature'));
            $rows = array();

            foreach($results as $result){
                $rows[] = array(
                    $result->name,
                    t($city->getTemp($result->latitude, $result->longitude))
                );
            }

            $block['content'] = theme('table',  array('header' => $header, 'rows' => $rows));

            break;
    }
    return $block;
}